/** Declaration file generated by dts-gen */

export function ExpressPeerServer(server: any, options: any): any;

export function PeerServer(options: any, callback: any): any;

export namespace ExpressPeerServer {
    const prototype: {
    };

}

export namespace PeerServer {
    const prototype: {
    };

}

